### PR TITLE
Add support for dogstatsd set values.

### PR DESCRIPTION
**Pull request by jonson**
I needed the dogstatsd set value feature so I added it.  It's running and reporting to datadog for me just fine.

Feel free to merge this in if this is of any value.

### CODE REVIEW

**Comment by ovesh** [comment]
From your javadoc, I don't understand how this is different from a gauge.
This sounds like a feature of dogstatsd that I don't know, but I couldn't find it documented anywhere. Can you link to its documentation?

**Comment by ovesh** [comment]
oh I see your comment now ("documentation is light, but looking at dogstatsd source, we can send string values here instead of numbers"). I'm going to verify this with datadog support before merging this.

**Comment by jonson** [comment]
Sorry, I should have posted more detail.  Sets are an extension to the statsd protocol:
http://docs.datadoghq.com/guides/dogstatsd/#sets

And require a different datagram format, as mentioned here:
http://docs.datadoghq.com/guides/dogstatsd/#metrics-1

And a few tests in the dogstatsd server code, the second sets one uses string values:
https://github.com/DataDog/dd-agent/blob/5.99.571/tests/core/test_dogstatsd.py#L253

**Comment by ovesh** [comment]
Oh, that's awesome. Can you add the first link to the javadoc?

**Comment by ovesh** [comment]
I just realized I accidentally closed this. Can you add the links to the javadoc so I can merge this?

**Comment by jonson** [comment]
Links added

**Pull request merged**
