### PR TITLE
Don't cache DNS resolution forever

### PR DESCRIPTION
**Pull request by matthewAURA**
We have a custom StatsD where we rely on DNS address changes to roll out new versions, the NonBlockingStatsDClient currently caches the DNS address resolution for its entire lifetime. We changed this to resolve before pushing data, thus relying solely on DNS caching within the JVM. The default caching time is implementation specific, however it can be overridden by a system property, to maintain the original behaviour (see [http://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html](http://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html)) Setting networkaddress.cache.ttl
to -1 caches DNS results forever. We now escape if the DNS resolution was unsuccessful, meaning that the ExceptionHandler will be called if the DNS resolution fails.

### CODE REVIEW

**Comment by ovesh** [comment]
I hope to be able to merge all open issues this week.

**Comment by ovesh** [comment]
Can you make the default behaviour be to set `networkaddress.cache.ttl` to -1, and overrideable?

**Comment by fakraemer** [comment]
[`networkaddress.cache.ttl`](http://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html) is a system property from stdlib, we should not set that in application code. We mentioned it here as one way for the consumer to retain old behaviour, but it is not the only way. If consumers want to cache name resolution forever, they can also just configure the IP address of the host. I don't see much value in adding code that would, depending on the configuration, cache the name resolution forever. If someone is providing DNS names, arguably they would like the application to be able to cope with address changes on the name somewhat gracefully. Personally I would just mention in the release notes that the behaviour changed this way, and explain how the old behaviour can be retained (preferring configuring the IP address since the system property will affect behaviour on the entire JVM).

**Comment by ovesh** [comment]
> we should not set that in application code.

good point.

> The default caching time is implementation specific

this is the part that scares me a little. I don't want a DNS lookup to happen too often. If possible, I'd like to keep backwards compatibility. Can you suggest a way where the old behavior is maintained by default?

**Comment by fakraemer** [comment]
@ovesh I understand the concern, I was selfishly hoping that you would accept the behavioural change. Reason being is that we consume this client over [metrics-datadog](https://github.com/coursera/metrics-datadog) which appears to be inactive, thus we are going to end up having to maintain a fork of this. I've raised a PR against Matt's repo, https://github.com/matthewAURA/java-dogstatsd-client/pull/1, would you mind having a quick look if you're OK with the changes? Once we merge these in they will become part of this PR.

**Comment by fakraemer** [comment]
@ovesh Thanks for merging this into master. Do you have any plans to cut a release any time soon?

**Comment by ovesh** [comment]
Thanks for the reminder. Published 2.0.14.

**Pull request merged**
