### PR TITLE
Adding in a default max queue size that is allowed to be queued before the current thread blocks

### PR DESCRIPTION
**Pull request by cowboygneox**
In response to #29.

### CODE REVIEW

**Comment by cowboygneox** [comment]
Because this is UDP, I can't believe that it would be possible to exceed 10,000, but with the JVM, it seems we should air towards _not_ consuming too much memory. The user of this lib can always make the amount larger.

**Comment by ovesh** [comment]
did you try benchmarking it locally to see if you can reach the limit?
Can you document what happens (from the api user's perspective) if the limit is reached?

**Comment by cowboygneox** [comment]
@ovesh You're keeping me honest. Let me see if I can build some kind of test that will create this situation. I'm already working on a timeout test, so let me see what I can do.

**Comment by cowboygneox** [comment]
@ovesh After thinking about it, maybe this isn't ever going to happen due to the fire-and-forget nature of UDP. Going down that vein, why would we need a timeout on a blocking queue? The only way the queue won't drain eventually is if there is some kind of catastrophic failure, right?

**Comment by ovesh** [comment]
Sorry for the silence here. This is still on my TODO list, but I'm a bit busy with other things at the moment.

**Comment by ovesh** [comment]
@masci, @irabinovitch, handing this over to you.

**Comment by masci** [comment]
@cowboygneox agree with not allocating a queue sized `Integer.MAX_VALUE`, still I'd prefer to have that valued defined as a constant somewhere, maybe a `private static final` variable in the same class. Can you update the code in this direction?

Regarding what happens if the queue is full, haven't tried but looking at the code I'd say we lose messages, since [here](https://github.com/indeedeng/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L699) the return value of `offer` is not evaluated and it is `false` when the queue is full.

As a side note, I'll pick your commits and merge into the new [upstream repo](https://github.com/DataDog/java-dogstatsd-client), so for future contributions you can open PRs directly there.

Thanks for your code!

**Comment by cowboygneox** [comment]
@masci My apologies for the long delay. I'm finally catching up with my list of TODO's. I have made the change you requested. Please let me know if I can assist in any other way.

**Pull request closed without merging**
